# Generated by Django 6.0 on 2026-01-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesartifact',
            name='processed_image',
            field=models.ImageField(default='undefined', upload_to='processed/'),
            preserve_default=False,
        ),
    ]
