# Generated by Django 6.0 on 2026-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_imagesartifact_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesartifact',
            name='uploaded_image',
            field=models.ImageField(default='', upload_to='uploaded/'),
            preserve_default=False,
        ),
    ]
